FROM node:current-alpine as builder

WORKDIR /app

COPY package.json .

RUN npm install
# --silent

COPY . .

RUN npm i -g @angular/cli

RUN ng build --configuration production --aot

FROM nginx:alpine

COPY --from=builder /app/dist/dstv-angular /usr/share/nginx/html

COPY config-nginx/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD nginx -g "daemon off;"
